{
 "title": "MY",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Filesystem memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{__name__=\"node_filesystem_avail_bytes\", device=\"/dev/sda3\", fstype=\"ext4\", instance=\"nodeexporter:9100\", job=\"nodeexporter\", mountpoint=\"/\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPULA 1/5/15",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "node_load1{job=\"nodeexporter\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_load5{job=\"nodeexporter\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_load15{job=\"nodeexporter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Free CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes{job='nodeexporter'}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "avg without (cpu)(irate(node_cpu_seconds_total{job=\"nodeexporter\",mode=\"idle\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}